### ISSUE TITLE
Failed to export spans - Failed to connect to localhost/127.0.0.1:9080

### ISSUE THREAD

**Issue by EvilAcid** [signalfx/splunk-otel-java#140]
## DeploymentConfig
```
- name: SIGNALFX_AGENT_HOST
   valueFrom:
     fieldRef:
       apiVersion: v1
       fieldPath: status.hostIP
- name: OTEL_EXPORTER_ZIPKIN_ENDPOINT
  value: "http://$(SIGNALFX_AGENT_HOST):9080/v1/trace"
- name: SIGNALFX_ENDPOINT_URL
  value: "http://$(SIGNALFX_AGENT_HOST):9080/v1/trace"
- name: OTEL_EXPORTER_ZIPKIN_SERVICE_NAME
  value: "${NAMESPACE}-${SERVICE_NAME}"
```

## ENV from POD
```
SIGNALFX_AGENT_HOST=10.176.44.179
OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://10.176.44.179:9080/v1/trace
SIGNALFX_ENDPOINT_URL=http://10.176.44.179:9080/v1/trace
```
I have tried both variables. they are set correctly but ignored by the agent and overwritten by the default values.

the connection from the pod to the endpoint is possible with a curl

## Log
```
{10:22:04,780} ERROR [stderr] (BatchSpanProcessor_WorkerThread-1) [opentelemetry.auto.trace 2021-03-24 10:22:04:780 +0100] [BatchSpanProcessor_WorkerThread-1] WARN io.opentelemetry.exporter.jaeger.thrift.JaegerThriftSpanExporter - Failed to export spans
{10:22:04,781} ERROR [stderr] (BatchSpanProcessor_WorkerThread-1) io.jaegertracing.internal.exceptions.SenderException: Could not send 3 spans
{10:22:04,781} ERROR [stderr] (BatchSpanProcessor_WorkerThread-1) 	at io.jaegertracing.thrift.internal.senders.HttpSender.send(HttpSender.java:69)
{10:22:04,781} ERROR [stderr] (BatchSpanProcessor_WorkerThread-1) 	at io.opentelemetry.exporter.jaeger.thrift.JaegerThriftSpanExporter.lambda$export$2(JaegerThriftSpanExporter.java:96)
{10:22:04,781} ERROR [stderr] (BatchSpanProcessor_WorkerThread-1) 	at java.base/java.util.HashMap.forEach(HashMap.java:1336)
{10:22:04,781} ERROR [stderr] (BatchSpanProcessor_WorkerThread-1) 	at io.opentelemetry.exporter.jaeger.thrift.JaegerThriftSpanExporter.export(JaegerThriftSpanExporter.java:90)
{10:22:04,781} ERROR [stderr] (BatchSpanProcessor_WorkerThread-1) 	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.exportCurrentBatch(BatchSpanProcessor.java:266)
{10:22:04,781} ERROR [stderr] (BatchSpanProcessor_WorkerThread-1) 	at io.opentelemetry.sdk.trace.export.BatchSpanProcessor$Worker.run(BatchSpanProcessor.java:201)
{10:22:04,781} ERROR [stderr] (BatchSpanProcessor_WorkerThread-1) 	at java.base/java.lang.Thread.run(Thread.java:834)
{10:22:04,781} ERROR [stderr] (BatchSpanProcessor_WorkerThread-1) Caused by: java.net.ConnectException: Failed to connect to localhost/127.0.0.1:9080
```

Why is my ENV overwriten by the Default endpoint and run in this Error?

> SignalFX-Agent v5.9.0 on Kubernets (Openshift 4.6) as Deamonset

> splunk-otel-java v0.9.0

**Comment by iNikem** [comment]
If you try to export span data to Zipkin endpoint, you have to select Zipkin exporter. See https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk-extensions/autoconfigure/README.md#zipkin-exporter

**Comment by EvilAcid** [comment]
I try diferent one.

I see my COnfig from the SignalFX-Agent has this additional Config:
```
    writer:
      traceExportFormat: sapm
```

**Comment by iNikem** [comment]
Let us get the first step right. Have you changed your config to use Zipkin exporter?

**Comment by EvilAcid** [comment]
Yes.
Here is my deployment Config:
```yaml
               - name: SIGNALFX_AGENT_HOST
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: status.hostIP
                - name: OTEL_EXPORTER_ZIPKIN_SERVICE_NAME
                  value: "${NAMESPACE}-${SERVICE_NAME}"
                - name: OTEL_EXPORTER_ZIPKIN_ENDPOINT
                  value: "http://$(SIGNALFX_AGENT_HOST):9080/v1/trace"
                - name: OTEL_TRACES_EXPORTER
                  value: "zipkin"
```

and strangely now data arrives... BUT without a Servicename..
i try for this following Settings:
```yaml
        - name: OTEL_EXPORTER_ZIPKIN_SERVICE_NAME
          value: test-1
        - name: SIGNALFX_SERVICE_NAME
          value: test-2
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=test-3
```

but on SignalFX i see only `unknown_service:java`

Logoutput on Startup is following:
```
OpenJDK 64-Bit Server VM warning: Sharing is only supported for boot loader classes because bootstrap classpath has been appended
[opentelemetry.auto.trace 2021-03-26 13:30:59:897 +0100] [main] INFO io.opentelemetry.javaagent.tooling.VersionLogger - opentelemetry-javaagent - version: splunk-0.9.0-otel-1.0.0
WARNING: Failed to instantiate LoggerFinder provider; Using default.
[0m[32m13:31:17,009 DEBUG [org.jboss.as.config] (MSC service thread 1-2) Configured system properties:
        io.opentelemetry.javaagent.slf4j.simpleLogger.dateTimeFormat = '[opentelemetry.auto.trace 'yyyy-MM-dd HH:mm:ss:SSS Z']'
	io.opentelemetry.javaagent.slf4j.simpleLogger.log.muzzleMatcher = OFF
	io.opentelemetry.javaagent.slf4j.simpleLogger.showDateTime = true
	otel.exporter.jaeger.endpoint = http://localhost:9080/v1/trace   # <<<----- WHY ? I think it is not used
	otel.metrics.exporter = none
	otel.propagators = b3multi
	otel.resource.os.description = Linux 4.18.0-193.41.1.el8_2.x86_64
	otel.resource.os.type = LINUX
	otel.resource.process.command_line = /usr/lib/jvm/java-11-openjdk-11.0.9.11-3.el8_3.x86_64:bin:java -D[Standalone] -Xlog:gc*:file=/opt/eap/standalone/log/gc.log:time,uptimemillis:filecount=5,filesize=3M -Xms63m -Xmx250m -XX:MetaspaceSize=96m -XX:MaxMetaspaceSize=200m .......
	otel.resource.process.executable.path = /usr/lib/jvm/java-11-openjdk-11.0.9.11-3.el8_3.x86_64:bin:java
	otel.resource.process.runtime.description = Red Hat, Inc. OpenJDK 64-Bit Server VM 11.0.9.1+1-LTS
	otel.resource.process.runtime.name = OpenJDK Runtime Environment
	otel.resource.process.runtime.version = 11.0.9.1+1-LTS
	otel.resource.service.name = test-3
	otel.resource.telemetry.auto.version = splunk-0.9.0-otel-1.0.0
	otel.resource.telemetry.sdk.language = java
	otel.resource.telemetry.sdk.name = opentelemetry
	otel.resource.telemetry.sdk.version = 1.0.0

```
