### ISSUE TITLE
Spring Boot v2.5.6 throwing exceptions

### ISSUE THREAD

**Issue by mcheng-splunk** [signalfx/splunk-otel-java#523]
When using the micrometer on a Spring Boot v.2.5.6 framework, application will throw exceptions as followed. However, if we reverted back to Spring Boot v2.3.4, there is no exception. 

In both scenario, the custom metrics are sent successfully to the Observability Cloud.

`-Dotel.instrumentation.tomcat-metrics.enabled=false` does remove the exception.

```[otel.javaagent 2021-11-10 14:01:20:067 +0800] [signalfx-metrics-publisher] WARN com.splunk.javaagent.shaded.io.micrometer.core.instrument.internal.DefaultGauge - Failed to apply the value function for the gauge 'executor.threads'. Note that subsequent logs will be logged at debug level.
java.lang.BootstrapMethodError: bootstrap method initialization exception
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:185)
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)
	at com.splunk.opentelemetry.instrumentation.tomcat.metrics.ThreadPoolMetrics$Suppliers.getCurrentThreads(ThreadPoolMetrics.java:90)
	at com.splunk.opentelemetry.instrumentation.tomcat.metrics.ThreadPoolMetrics$Suppliers.access$700(ThreadPoolMetrics.java:82)
	at com.splunk.opentelemetry.instrumentation.tomcat.metrics.ThreadPoolMetrics.lambda$createMeters$0(ThreadPoolMetrics.java:60)
	at com.splunk.javaagent.shaded.io.micrometer.core.instrument.Gauge.lambda$builder$0(Gauge.java:58)
	at com.splunk.javaagent.shaded.io.micrometer.core.instrument.StrongReferenceGaugeFunction.applyAsDouble(StrongReferenceGaugeFunction.java:47)
	at com.splunk.javaagent.shaded.io.micrometer.core.instrument.internal.DefaultGauge.value(DefaultGauge.java:54)
	at com.splunk.javaagent.shaded.io.micrometer.signalfx.SignalFxMeterRegistry.addGauge(SignalFxMeterRegistry.java:178)
	at com.splunk.javaagent.shaded.io.micrometer.core.instrument.Meter.match(Meter.java:107)
	at com.splunk.javaagent.shaded.io.micrometer.signalfx.SignalFxMeterRegistry.lambda$publish$1(SignalFxMeterRegistry.java:101)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$SubList$2.forEachRemaining(ArrayList.java:1481)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.splunk.javaagent.shaded.io.micrometer.signalfx.SignalFxMeterRegistry.publish(SignalFxMeterRegistry.java:112)
	at com.splunk.javaagent.shaded.io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely(PushMeterRegistry.java:52)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.invoke.LambdaConversionException: Invalid receiver type class org.apache.tomcat.util.threads.ThreadPoolExecutor; not a subtype of implementation type class java.util.concurrent.ThreadPoolExecutor
	at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:268)
	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:327)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:127)
	... 28 more
[otel.javaagent 2021-11-10 14:01:20:308 +0800] [signalfx-metrics-publisher] WARN com.splunk.javaagent.shaded.io.micrometer.signalfx.SignalFxMeterRegistry - failed to send metrics
java.lang.BootstrapMethodError: bootstrap method initialization exception
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:185)
	at java.base/java.lang.invoke.CallSite.makeSite(CallSite.java:315)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSiteImpl(MethodHandleNatives.java:281)
	at java.base/java.lang.invoke.MethodHandleNatives.linkCallSite(MethodHandleNatives.java:271)
	at com.splunk.opentelemetry.instrumentation.tomcat.metrics.ThreadPoolMetrics$Suppliers.getCompletedTasks(ThreadPoolMetrics.java:114)
	at com.splunk.opentelemetry.instrumentation.tomcat.metrics.ThreadPoolMetrics$Suppliers.access$100(ThreadPoolMetrics.java:82)
	at com.splunk.opentelemetry.instrumentation.tomcat.metrics.ThreadPoolMetrics.lambda$createMeters$6(ThreadPoolMetrics.java:66)
	at com.splunk.opentelemetry.javaagent.bootstrap.metrics.CounterSemanticConvention.lambda$create$0(CounterSemanticConvention.java:48)
  1 java -javaagent:splunk-otel-javaagent-all.jar -Dsplunk.metrics.enabled=true -Dsplunk.metrics.export.interval=10s  -Dotel.instrumentation.tomcat-metrics.enabled=false -Dsplunk.profiler.enabled=true -Dotel.resource.attributes=deployment.environment=mch	at com.splunk.javaagent.shaded.io.micrometer.core.instrument.step.StepFunctionCounter.count(StepFunctionCounter.java:43)
	at com.splunk.javaagent.shaded.io.micrometer.signalfx.SignalFxMeterRegistry.addFunctionCounter(SignalFxMeterRegistry.java:186)
	at com.splunk.javaagent.shaded.io.micrometer.core.instrument.Meter.match(Meter.java:117)
	at com.splunk.javaagent.shaded.io.micrometer.signalfx.SignalFxMeterRegistry.lambda$publish$1(SignalFxMeterRegistry.java:101)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$SubList$2.forEachRemaining(ArrayList.java:1481)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at com.splunk.javaagent.shaded.io.micrometer.signalfx.SignalFxMeterRegistry.publish(SignalFxMeterRegistry.java:112)
	at com.splunk.javaagent.shaded.io.micrometer.core.instrument.push.PushMeterRegistry.publishSafely(PushMeterRegistry.java:52)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Thread.java:831)
Caused by: java.lang.invoke.LambdaConversionException: Invalid receiver type class org.apache.tomcat.util.threads.ThreadPoolExecutor; not a subtype of implementation type class java.util.concurrent.ThreadPoolExecutor
	at java.base/java.lang.invoke.AbstractValidatingLambdaMetafactory.validateMetafactoryArgs(AbstractValidatingLambdaMetafactory.java:268)
	at java.base/java.lang.invoke.LambdaMetafactory.metafactory(LambdaMetafactory.java:327)
	at java.base/java.lang.invoke.BootstrapMethodInvoker.invoke(BootstrapMethodInvoker.java:127)
	... 27 more```

**Comment by breedx-splk** [comment]
Thanks for letting us know about this. I have been able to reproduce this and am working on a fix. 👍🏻
