### ISSUE TITLE
A lot of errors when sending spans

### ISSUE THREAD

**Issue by gitCommitAndHit** [signalfx/splunk-otel-java#61]
Version: latest(Release v0.4.0)
JAVA: 11
SPRINGBOOT: 2.2.6.RELEASE

Hi we trying migrate from signalfx to splunk, but after runing `exec java -javaagent:/splunk-otel-javaagent-all.jar  ${JAVA_EXTRA_OPTS} -jar -Xmx${JAVA_XMX}  /app.jar` we see a lot of logs 

```[opentelemetry.auto.trace 2020-12-11 09:48:58:412 +0000] [OkHttp http://172.17.0.1:9080/...] WARN io.opentelemetry.exporter.zipkin.ZipkinSpanExporter - Failed to export spans
java.lang.RuntimeException: response for null failed: error handling gzip compressed request EOF	
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)	
	at zipkin2.reporter.okhttp3.HttpCall.parseResponse(HttpCall.java:93)	
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)	
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)	
	at zipkin2.reporter.okhttp3.HttpCall$V2CallbackAdapter.onResponse(HttpCall.java:68) 
```
Do you have any suggestion what could be reason of it?

**Comment by iNikem** [comment]
SignalFx used Zipkin exporter by default. Recent versions of Splunk distribution use Jaeger over Thrift. You can either configure your data destination to accept it and then configure `otel.exporter.jaeger.endpoint` as described [here](https://github.com/signalfx/splunk-otel-java#jaeger-exporter). Or explicitly use Zipkin exporter as described [here](https://github.com/open-telemetry/opentelemetry-java-instrumentation#zipkin-exporter)

**Comment by gitCommitAndHit** [comment]
I already set up zipkin as described, in docker it runs like
```
SIGNALFX_AGENT_HOST=$(route -n | awk '/UG[ \t]/{print $2}')
export OTEL_EXPORTER=zipkin
export OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://${SIGNALFX_AGENT_HOST}:9080/v1/trace

exec java -javaagent:/splunk-otel-javaagent-all.jar ${JAVA_EXTRA_OPTS} -jar -Xmx${JAVA_XMX} -XX:+UseConcMarkSweepGC /app.jar```
OTEL_EXPORTER_ZIPKIN_SERVICE_NAME passed in JAVA_EXTRA_OPTS

**Comment by gitCommitAndHit** [comment]
By the way we use SIGNALFX_ACCESS_TOKEN param, is it still not renamed? 
Also we use signalfx-forwarder, can it be that it send not gziped response? if yes how we should configure it then? configuration of it is 
```
 - type: signalfx-forwarder
    # Specify the hostname:port where the Smart Agent receives traces.
    listenAddress: "0.0.0.0:9080"
```

**Comment by breedx-splk** [comment]
Hi @gitCommitAndHit. We are coming up on a year of little activity on this issue. We've had many releases since this was filed. Were you able to work it out and/or try the latest release?

**Comment by breedx-splk** [comment]
Closing due to inactivity. @gitCommitAndHit please reopen if you'd like to continue the discussion and update us on the current state. Thanks!
